/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neusoft_particle_ObjectJNI */

#ifndef _Included_com_neusoft_particle_ObjectJNI
#define _Included_com_neusoft_particle_ObjectJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_neusoft_particle_ObjectJNI
 * Method:    jni_initialize
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_neusoft_particle_ObjectJNI_jni_1initialize
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_neusoft_particle_ObjectJNI
 * Method:    jni_drawframe
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_neusoft_particle_ObjectJNI_jni_1drawframe
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
